services:
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - "rabbitmq_data:/data"
        networks:
            - backend
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - "27017:27017"
        networks:
            - backend
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
            - ME_CONFIG_BASICAUTH_USERNAME=dev
            - ME_CONFIG_BASICAUTH_PASSWORD=dev
        depends_on:
            - mongo
        ports:
            - "7777:8081"
        networks:
            - backend
    gateway:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ADDR=nginx:443
        ports:
            - "8888:8888"
        restart: unless-stopped
        depends_on:
            - mongo-express
            - rabbitmq
        networks:
            - backend
    order-0:
        build:
            context: .
            dockerfile: order/Dockerfile
        environment:
            - PORT=8889
        restart: unless-stopped
        depends_on:
            - gateway
        networks:
            - backend
    order-1:
        build:
            context: .
            dockerfile: order/Dockerfile
        environment:
            - PORT=8889
        restart: unless-stopped
        depends_on:
            - gateway
        networks:
            - backend
    nginx:
        build: nginx
        depends_on:
            - order-0
            - order-1
        networks:
            - backend
    payment:
        build:
            context: .
            dockerfile: payment/Dockerfile
        restart: unless-stopped
        depends_on:
            - gateway
        networks:
            - backend
    kitchen:
        build:
            context: .
            dockerfile: kitchen/Dockerfile
        restart: unless-stopped
        depends_on:
            - gateway
        networks:
            - backend
volumes:
    rabbitmq_data:

networks:
  backend: